import {
	BookOpen,
	GraduationCap,
	Building2,
	Briefcase,
	Globe,
	Users,
	Calendar,
	Book,
	School,
	Lightbulb,
	Rocket,
	Microscope,
	Beaker,
	Cpu,
	Code,
	Database,
	PenToolIcon as Tool,
	Camera,
	Film,
	Music,
	Heart,
	Brain,
	Puzzle,
	Leaf,
	Recycle,
	Zap,
	Building,
	Home,
	Plane,
	Bus,
	Compass,
	Map as MapIcon,
	Wallet,
	DollarSign,
	BarChart,
	TrendingUp,
	Target,
	Smartphone,
	Wrench,
	Ruler,
	FileText,
	MessageCircle,
	Gift,
	Clipboard,
	Medal,
	Clock,
	Utensils,
	Handshake,
} from "lucide-react";
import type { Category } from "./components/CategoryCard";

// アイコン名と実体のマッピング
const iconMap = {
	BookOpen,
	GraduationCap,
	Building2,
	Briefcase,
	Globe,
	Users,
	Calendar,
	Book,
	School,
	Lightbulb,
	Rocket,
	Microscope,
	Beaker,
	Cpu,
	Code,
	Database,
	Tool,
	Camera,
	Film,
	Music,
	Heart,
	Brain,
	Puzzle,
	Leaf,
	Recycle,
	Zap,
	Building,
	Home,
	Plane,
	Bus,
	Compass,
	MapIcon,
	Wallet,
	DollarSign,
	BarChart,
	TrendingUp,
	Target,
	Smartphone,
	Wrench,
	Ruler,
	FileText,
	MessageCircle,
	Gift,
	Clipboard,
	Medal,
	Clock,
	Utensils,
	Handshake,
};

// カラー名のマッピング
const colorMap = {
	emerald500: "text-emerald-500",
	blue500: "text-blue-500",
	purple500: "text-purple-500",
	orange500: "text-orange-500",
	indigo500: "text-indigo-500",
	blue600: "text-blue-600",
	cyan500: "text-cyan-500",
	red500: "text-red-500",
	green500: "text-green-500",
	// ...必要に応じて追加...
};

// カテゴリー定義の型
export interface CategoryDef {
	id: string;
	title: string;
	description: string;
	icon: keyof typeof iconMap;
	color: string;
}

// メインカテゴリー
export const mainCategories: Category[] = [
	{
		id: "about",
		title: "進化するKITとは？",
		description: "KITの教育方針",
		icon: iconMap.Lightbulb,
		color: colorMap.emerald500,
	},
	{
		id: "new-faculty",
		title: "新学部・学科",
		description: "学部・学科の構成",
		icon: iconMap.School,
		color: colorMap.blue500,
	},
	{
		id: "learning",
		title: "学びの現場",
		description: "実践的な学習",
		icon: iconMap.BookOpen,
		color: colorMap.purple500,
	},
	{
		id: "campus-life",
		title: "キャンパス",
		description: "学生生活の実情",
		icon: iconMap.Building2,
		color: colorMap.orange500,
	},
	{
		id: "admission",
		title: "入試情報",
		description: "受験準備情報",
		icon: iconMap.GraduationCap,
		color: colorMap.indigo500,
	},
	{
		id: "career",
		title: "進路",
		description: "就職・進学",
		icon: iconMap.Target,
		color: colorMap.blue600,
	},
	{
		id: "global",
		title: "グローバル",
		description: "国際交流・留学",
		icon: iconMap.Globe,
		color: colorMap.cyan500,
	},
	{
		id: "research",
		title: "研究活動",
		description: "研究所・プロジェクト",
		icon: iconMap.Microscope,
		color: colorMap.red500,
	},
	{
		id: "tuition",
		title: "学費・奨学金",
		description: "費用と支援",
		icon: iconMap.Wallet,
		color: colorMap.green500,
	},
];

// サブカテゴリーのマッピング
export const subCategories: Record<string, Category[]> = {
	about: [
		{
			id: "bunri",
			title: "文理融合",
			description: "多様な視点の融合",
			icon: iconMap.Puzzle,
			color: "text-emerald-600",
		},
		{
			id: "shakaijissou",
			title: "社会実装",
			description: "実践で課題解決",
			icon: iconMap.Rocket,
			color: "text-blue-600",
		},
		{
			id: "kyousou",
			title: "共創学修",
			description: "世代・分野を超えた学び",
			icon: iconMap.Users,
			color: "text-orange-600",
		},
		{
			id: "sxgx",
			title: "SX・GX・DX",
			description: "持続可能な変革",
			icon: iconMap.Recycle,
			color: "text-red-600",
		},
	],
	"new-faculty": [
		{
			id: "infoDesign",
			title: "情報デザイン学部",
			description: "社会のニーズに応えるデザイン。",
			icon: iconMap.Tool,
			color: "text-blue-600",
		},
		{
			id: "mediaInfo",
			title: "メディア情報学部",
			description: "メディアと情報技術の融合。",
			icon: iconMap.Camera,
			color: "text-purple-600",
		},
		{
			id: "infoTech",
			title: "情報理工学部",
			description: "情報技術で未来を切り拓く。",
			icon: iconMap.Cpu,
			color: "text-indigo-600",
		},
		{
			id: "bioChem",
			title: "バイオ・化学部",
			description: "生命と化学の可能性を探求。",
			icon: iconMap.Beaker,
			color: "text-green-600",
		},
		{
			id: "eng",
			title: "工学部",
			description: "ものづくりで社会を支える。",
			icon: iconMap.Wrench,
			color: "text-orange-600",
		},
		{
			id: "arch",
			title: "建築学部",
			description: "快適な空間をデザインする。",
			icon: iconMap.Home,
			color: "text-teal-600",
		},
	],
	learning: [
		{
			id: "educationMethod",
			title: "教育手法",
			description: "課題解決プログラム",
			icon: iconMap.Target,
			color: "text-blue-500",
		},
		{
			id: "collab",
			title: "連携学修",
			description: "早期研究体験",
			icon: iconMap.Puzzle,
			color: "text-green-600",
		},
		{
			id: "intern",
			title: "インターンシップ",
			description: "企業実務体験",
			icon: iconMap.Briefcase,
			color: "text-orange-600",
		},
		{
			id: "curriculum",
			title: "カリキュラム",
			description: "全体像の紹介",
			icon: iconMap.FileText,
			color: "text-emerald-600",
		},
	],
	"campus-life": [
		{
			id: "dining",
			title: "学食・カフェ",
			description: "食堂情報・メニュー",
			icon: iconMap.Utensils,
			color: "text-yellow-600",
		},
		{
			id: "dorm",
			title: "学生寮",
			description: "住まい支援情報",
			icon: iconMap.Building,
			color: "text-teal-600",
		},
		{
			id: "extracurricular",
			title: "課外活動",
			description: "サークル・プロジェクト",
			icon: iconMap.Music,
			color: "text-pink-500",
		},
		{
			id: "support",
			title: "生活支援",
			description: "健康・サポート",
			icon: iconMap.Heart,
			color: "text-gray-500",
		},
		{
			id: "bus",
			title: "キャンパス間バス",
			description: "運行情報",
			icon: iconMap.Bus,
			color: "text-green-500",
		},
	],
	admission: [
		{
			id: "admission",
			title: "入試",
			description: "入試情報",
			icon: iconMap.GraduationCap,
			color: "text-indigo-500",
		},
	],
	career: [
		{
			id: "career",
			title: "進路",
			description: "就職・進学",
			icon: iconMap.Target,
			color: "text-blue600",
		},
	],
	global: [
		{
			id: "global",
			title: "グローバル",
			description: "国際交流・留学",
			icon: iconMap.Globe,
			color: "text-cyan-500",
		},
	],
	research: [
		{
			id: "research",
			title: "研究活動",
			description: "研究所・プロジェクト",
			icon: iconMap.Microscope,
			color: "text-red-500",
		},
	],
	tuition: [
		{
			id: "tuition",
			title: "学費・奨学金",
			description: "費用と支援",
			icon: iconMap.Wallet,
			color: "text-green-500",
		},
	],
};

// サブサブカテゴリーのマッピング
export const subSubCategories: Record<string, Category[]> = {
	// about サブカテゴリー
	bunri: [
		{
			id: "bunri-komyunikeeshon",
			title: "コミュニケーション",
			description: "学生交流で新発見。",
			icon: iconMap.MessageCircle,
			color: "text-emerald-700",
		},
		{
			id: "bunri-aratanakachisouzou",
			title: "価値創造",
			description: "革新的視点の獲得。",
			icon: iconMap.Lightbulb,
			color: "text-orange-700",
		},
		{
			id: "bunri-kadaitsuikyuu",
			title: "課題追求",
			description: "社会課題の解決。",
			icon: iconMap.Target,
			color: "text-blue-700",
		},
	],
	shakaijissou: [
		{
			id: "shakaijissou-jissenkyouiku",
			title: "実践教育",
			description: "実践的なスキル。",
			icon: Tool,
			color: "text-blue-700",
		},
		{
			id: "shakaijissou-sangakukyoudo",
			title: "産学連携",
			description: "企業連携研究。",
			icon: iconMap.Handshake,
			color: "text-indigo-700",
		},
	],
	kyousou: [
		{
			id: "kyousou-sedai",
			title: "世代",
			description: "世代を超えた学び。",
			icon: iconMap.Users,
			color: "text-purple-700",
		},
		{
			id: "kyousou-bunya",
			title: "分野",
			description: "分野を超えた学び。",
			icon: iconMap.Puzzle,
			color: "text-orange-700",
		},
		{
			id: "kyousou-bunka",
			title: "文化",
			description: "文化を超えた学び。",
			icon: iconMap.Globe,
			color: "text-blue-700",
		},
	],
	sxgx: [
		{
			id: "sxgx-sx",
			title: "SX（サステナビリティ・トランスフォーメーション）",
			description: "環境と社会の持続可能性。",
			icon: iconMap.Leaf,
			color: "text-green-700",
		},
		{
			id: "sxgx-gx",
			title: "GX（グリーン・トランスフォーメーション）",
			description: "脱炭素社会への移行。",
			icon: iconMap.Recycle,
			color: "text-teal-700",
		},
		{
			id: "sxgx-dx",
			title: "DX（デジタル・トランスフォーメーション）",
			description: "デジタル技術による変革。",
			icon: iconMap.Cpu,
			color: "text-purple-700",
		},
	],
	// 情報デザイン
	infoDesign: [
		{
			id: "infoDesign-keieijoho",
			title: "経営情報学科",
			description: "経営と情報を融合。",
			icon: iconMap.BarChart,
			color: "text-blue-700",
		},
		{
			id: "infoDesign-kankyoudesign",
			title: "環境デザイン創成学科",
			description: "持続可能な社会をデザイン。",
			icon: iconMap.Leaf,
			color: "text-emerald-700",
		},
	],
	// メディア情報
	mediaInfo: [
		{
			id: "mediaInfo-mediajouhou",
			title: "メディア情報学科",
			description: "多様なメディア表現を追求。",
			icon: iconMap.Film,
			color: "text-purple-700",
		},
		{
			id: "mediaInfo-shinrijouhou",
			title: "心理情報デザイン学科",
			description: "人の心を理解しデザイン。",
			icon: iconMap.Brain,
			color: "text-amber-700",
		},
	],
	// 情報理工学
	infoTech: [
		{
			id: "infoTech-johokogaku",
			title: "情報工学科",
			description: "情報科学の基盤を築く。",
			icon: iconMap.Code,
			color: "text-indigo-700",
		},
		{
			id: "infoTech-chinousystem",
			title: "知能情報システム学科",
			description: "AIと知能システムを開発。",
			icon: iconMap.Database,
			color: "text-blue-700",
		},
		{
			id: "infoTech-robotics",
			title: "ロボティクス学科",
			description: "ロボット技術で社会に貢献。",
			icon: iconMap.Cpu,
			color: "text-green-700",
		},
	],
	// バイオ・化学
	bioChem: [
		{
			id: "bioChem-ouyoukagaku",
			title: "環境・応用化学科",
			description: "環境に配慮した化学技術。",
			icon: iconMap.Beaker,
			color: "text-green-700",
		},
		{
			id: "bioChem-seimeibio",
			title: "生命・応用バイオ学科",
			description: "生命科学の応用を研究。",
			icon: iconMap.Microscope,
			color: "text-emerald-700",
		},
	],
	// 工学部
	eng: [
		{
			id: "eng-kikaikougaku",
			title: "機械工学科",
			description: "機械システムの設計と開発。",
			icon: iconMap.Tool,
			color: "text-orange-700",
		},
		{
			id: "eng-senshinkikai",
			title: "先進機械システム工学科",
			description: "高度な機械システムを創造。",
			icon: iconMap.Cpu,
			color: "text-red-700",
		},
		{
			id: "eng-koukuuuchuu",
			title: "航空宇宙工学科",
			description: "航空宇宙分野の技術を学ぶ。",
			icon: iconMap.Plane,
			color: "text-indigo-700",
		},
		{
			id: "eng-denkienergy",
			title: "電気エネルギーシステム工学科",
			description: "エネルギー技術の革新を担う。",
			icon: iconMap.Zap,
			color: "text-blue-700",
		},
		{
			id: "eng-denshijouhou",
			title: "電子情報システム工学科",
			description: "情報通信技術の専門家を育成。",
			icon: iconMap.Smartphone,
			color: "text-green-700",
		},
		{
			id: "eng-kankyodoken",
			title: "環境土木工学科",
			description: "持続可能な社会基盤を構築。",
			icon: iconMap.Building,
			color: "text-teal-700",
		},
	],
	// 建築学部
	arch: [
		{
			id: "arch-kenchikukougaku",
			title: "建築学科",
			description: "建築の構造と技術を学ぶ。",
			icon: iconMap.Ruler,
			color: "text-teal-700",
		},
		{
			id: "arch-kenchikudesign",
			title: "建築デザイン学科",
			description: "建築デザインの創造性を磨く。",
			icon: iconMap.Tool,
			color: "text-blue-700",
		},
	],
	// learning
	educationMethod: [
		{
			id: "educationMethod-projDesign",
			title: "プロジェクトデザイン教育",
			description: "実践的な問題解決能力を育成。",
			icon: iconMap.Target,
			color: "text-blue-700",
		},
		{
			id: "educationMethod-cdio",
			title: "CDIO (Conceive, Design, Implement, Operate)",
			description: "実践的な工学教育。",
			icon: iconMap.Puzzle,
			color: "text-purple-700",
		},
	],
	// collab
	collab: [
		{
			id: "collab-coop",
			title: "コーオプ教育",
			description: "企業との連携による実践教育。",
			icon: iconMap.Handshake,
			color: "text-green-700",
		},
	],
	// intern
	intern: [
		{
			id: "intern-domestic",
			title: "国内企業実習",
			description: "国内企業での実務経験。",
			icon: iconMap.Briefcase,
			color: "text-orange-700",
		},
		{
			id: "intern-overseas",
			title: "海外インターンシップ",
			description: "グローバルな視点を養う。",
			icon: iconMap.Plane,
			color: "text-blue-700",
		},
	],
	// curriculum
	curriculum: [
		{
			id: "curriculum-basic",
			title: "基礎教育",
			description: "幅広い知識を習得。",
			icon: iconMap.Book,
			color: "text-emerald-700",
		},
		{
			id: "curriculum-professional",
			title: "専門教育",
			description: "専門分野を深く学ぶ。",
			icon: iconMap.Code,
			color: "text-blue-700",
		},
		{
			id: "curriculum-project",
			title: "プロジェクト科目",
			description: "実践的な課題に取り組む。",
			icon: iconMap.Rocket,
			color: "text-gray-700",
		},
	],
	// campus-life サブカテゴリー
	dining: [
		{
			id: "dining-laterra",
			title: "LA TERRA",
			description: "扇が丘キャンパス21号館の大型食堂。",
			icon: iconMap.Utensils,
			color: "text-yellow-700",
		},
		{
			id: "dining-ilsole",
			title: "IL SOLE",
			description: "扇が丘キャンパス21号館のカフェテリア。",
			icon: iconMap.Utensils,
			color: "text-yellow-700",
		},
		{
			id: "dining-energy",
			title: "ENERGY",
			description: "やつかほリサーチキャンパス62号館のレストラン。",
			icon: iconMap.Utensils,
			color: "text-yellow-700",
		},
		{
			id: "dining-acqua",
			title: "ACQUA",
			description: "扇が丘キャンパス27号館の売店。",
			icon: iconMap.Utensils,
			color: "text-yellow-700",
		},
	],
	dorm: [
		{
			id: "dorm-kit",
			title: "KIT指定寮",
			description: "大学指定の学生専用アパート・寮。",
			icon: iconMap.Home,
			color: "text-teal-700",
		},
		{
			id: "dorm-support",
			title: "住まいサポートデスク",
			description: "住居相談所。",
			icon: iconMap.Compass,
			color: "text-gray-700",
		},
	],
	extracurricular: [
		{
			id: "extracurricular-yumekobo",
			title: "夢考房プロジェクト",
			description: "学生が正課外で参加できるプロジェクト。",
			icon: iconMap.Rocket,
			color: "text-pink-700",
		},
		{
			id: "extracurricular-projects",
			title: "プロジェクト",
			description: "学生主体の実践活動。",
			icon: iconMap.Rocket,
			color: "text-blue-700",
		},
		{
			id: "extracurricular-clubs",
			title: "クラブ・サークル",
			description: "体育系から文化系まで約60の団体。",
			icon: iconMap.Users,
			color: "text-pink-700",
		},
		{
			id: "extracurricular-festival",
			title: "工大祭",
			description: "学生主体で企画運営される大学祭。",
			icon: iconMap.Music,
			color: "text-pink-700",
		},
	],
	support: [
		{
			id: "support-station",
			title: "学生ステーション",
			description: "学生生活をサポート。",
			icon: iconMap.Heart,
			color: "text-gray-700",
		},
		{
			id: "support-procedure",
			title: "手続き・証明発行",
			description: "各種手続き。",
			icon: iconMap.Clipboard,
			color: "text-gray-700",
		},
	],
	bus: [
		{
			id: "bus-timetable",
			title: "時刻表",
			description: "運行スケジュール。",
			icon: iconMap.Clock,
			color: "text-green-700",
		},
	],
	admission: [
		{
			id: "admission-newfac",
			title: "新学部設置",
			description: "新学部設置。",
			icon: iconMap.School,
			color: "text-indigo-700",
		},
		{
			id: "admission-scholarship",
			title: "奨学金制度充実",
			description: "奨学金制度充実。",
			icon: iconMap.Gift,
			color: "text-yellow-700",
		},
		{
			id: "admission-sougou",
			title: "総合選抜方式",
			description: "総合選抜方式。",
			icon: iconMap.Users,
			color: "text-orange-700",
		},
		{
			id: "admission-ippan",
			title: "一般試験A改革",
			description: "一般試験A改革。",
			icon: iconMap.FileText,
			color: "text-blue-700",
		},
		{
			id: "admission-todoufuken",
			title: "都道府県選抜",
			description: "都道府県選抜。",
			icon: iconMap.MapIcon,
			color: "text-indigo-700",
		},
		{
			id: "admission-list",
			title: "各種入試制度",
			description: "各種入試制度。",
			icon: iconMap.Clipboard,
			color: "text-violet-700",
		},
		{
			id: "admission-quota",
			title: "募集人数",
			description: "募集人数。",
			icon: iconMap.Users,
			color: "text-orange-700",
		},
		{
			id: "admission-examSchedule",
			title: "試験日程",
			description: "試験日程。",
			icon: iconMap.Calendar,
			color: "text-indigo-700",
		},
		{
			id: "admission-application",
			title: "出願手続",
			description: "出願手続。",
			icon: iconMap.Clipboard,
			color: "text-blue-700",
		},
		{
			id: "admission-pastData",
			title: "過去データ",
			description: "過去データ。",
			icon: iconMap.BarChart,
			color: "text-blue-700",
		},
	],
	career: [
		{
			id: "career-seminar",
			title: "初年次セミナー",
			description: "キャリア形成の基礎。",
			icon: iconMap.Book,
			color: "text-gray-700",
		},
		{
			id: "career-careerCenter",
			title: "キャリア支援",
			description: "就職活動をサポート。",
			icon: iconMap.Compass,
			color: "text-gray-700",
		},
		{
			id: "career-employment",
			title: "就職実績",
			description: "卒業生の進路。",
			icon: iconMap.TrendingUp,
			color: "text-blue-700",
		},
	],
	global: [
		{
			id: "global-studyabroad",
			title: "留学支援",
			description: "海外留学プログラム。",
			icon: iconMap.Plane,
			color: "text-blue-700",
		},
		{
			id: "global-english",
			title: "英語教育",
			description: "グローバルなコミュニケーション能力。",
			icon: iconMap.MessageCircle,
			color: "text-amber-700",
		},
		{
			id: "global-exchange",
			title: "国際交流",
			description: "海外大学との交流。",
			icon: iconMap.Globe,
			color: "text-cyan-700",
		},
	],
	research: [
		{
			id: "research-activities",
			title: "研究活動",
			description: "最先端の研究に挑戦。",
			icon: iconMap.Microscope,
			color: "text-red-700",
		},
	],
	tuition: [
		{
			id: "tuition-fee",
			title: "学費",
			description: "学費に関する情報。",
			icon: iconMap.DollarSign,
			color: "text-blue-700",
		},
		{
			id: "tuition-scholarship",
			title: "特別奨学生制度",
			description: "学業優秀な学生を支援。",
			icon: iconMap.Medal,
			color: "text-yellow-700",
		},
		{
			id: "tuition-newScholarship",
			title: "新奨学金制度",
			description: "経済的な支援を強化。",
			icon: iconMap.Gift,
			color: "text-green-700",
		},
	],
};
