import {
	BarChart,
	Beaker,
	Book,
	BookOpen,
	Brain,
	Briefcase,
	Building,
	Building2,
	Bus,
	Calendar,
	Camera,
	Clipboard,
	Clock,
	Code,
	Compass,
	Cpu,
	Database,
	DollarSign,
	FileText,
	Film,
	Gift,
	Globe,
	GraduationCap,
	Handshake,
	Heart,
	Home,
	Leaf,
	Lightbulb,
	Map as MapIcon,
	Medal,
	MessageCircle,
	Microscope,
	Music,
	Plane,
	Puzzle,
	Recycle,
	Rocket,
	Ruler,
	School,
	Smartphone,
	Target,
	PenToolIcon as Tool,
	TrendingUp,
	Users,
	Utensils,
	Wallet,
	Wrench,
	Zap,
} from "lucide-react";
import type { Category } from "./components/CategoryCard";

// アイコン名と実体のマッピング
const iconMap = {
	BookOpen,
	GraduationCap,
	Building2,
	Briefcase,
	Globe,
	Users,
	Calendar,
	Book,
	School,
	Lightbulb,
	Rocket,
	Microscope,
	Beaker,
	Cpu,
	Code,
	Database,
	Tool,
	Camera,
	Film,
	Music,
	Heart,
	Brain,
	Puzzle,
	Leaf,
	Recycle,
	Zap,
	Building,
	Home,
	Plane,
	Bus,
	Compass,
	MapIcon,
	Wallet,
	DollarSign,
	BarChart,
	TrendingUp,
	Target,
	Smartphone,
	Wrench,
	Ruler,
	FileText,
	MessageCircle,
	Gift,
	Clipboard,
	Medal,
	Clock,
	Utensils,
	Handshake,
};

// カラー名のマッピング
const colorMap = {
	emerald500: "text-emerald-500",
	blue500: "text-blue-500",
	purple500: "text-purple-500",
	orange500: "text-orange-500",
	indigo500: "text-indigo-500",
	blue600: "text-blue-600",
	cyan500: "text-cyan-500",
	red500: "text-red-500",
	green500: "text-green-500",
	// ...必要に応じて追加...
};

// カテゴリー定義の型
export interface CategoryDef {
	id: string;
	titleKey: string;
	descriptionKey: string;
	icon: keyof typeof iconMap;
	color: string;
}

// メインカテゴリー
export const mainCategories: Category[] = [
	{
		id: "about",
		title: "evolvingKit",
		description: "kitPolicy",
		icon: iconMap.Lightbulb,
		color: colorMap.emerald500,
	},
	{
		id: "new-faculty",
		title: "newFaculties",
		description: "facultyStructure",
		icon: iconMap.School,
		color: colorMap.blue500,
	},
	{
		id: "learning",
		title: "learningEnvironment",
		description: "practicalLearning",
		icon: iconMap.BookOpen,
		color: colorMap.purple500,
	},
	{
		id: "campus-life",
		title: "campus",
		description: "studentLife",
		icon: iconMap.Building2,
		color: colorMap.orange500,
	},
	{
		id: "admission",
		title: "admissionsInfo",
		description: "examPrep",
		icon: iconMap.GraduationCap,
		color: colorMap.indigo500,
	},
	{
		id: "career",
		title: "careerPaths",
		description: "employment",
		icon: iconMap.Target,
		color: colorMap.blue600,
	},
	{
		id: "global",
		title: "global",
		description: "internationalExchange",
		icon: iconMap.Globe,
		color: colorMap.cyan500,
	},
	{
		id: "research",
		title: "researchActivities",
		description: "researchInstitutes",
		icon: iconMap.Microscope,
		color: colorMap.red500,
	},
	{
		id: "tuition",
		title: "tuition",
		description: "costsSupport",
		icon: iconMap.Wallet,
		color: colorMap.green500,
	},
];

// サブカテゴリーのマッピング
export const subCategories: Record<string, Category[]> = {
	about: [
		{
			id: "bunri",
			title: "fusionOfArtsAndSciences",
			description: "integrationOfPerspectives",
			icon: iconMap.Puzzle,
			color: "text-emerald-600",
		},
		{
			id: "shakaijissou",
			title: "socialImplementation",
			description: "problemSolving",
			icon: iconMap.Rocket,
			color: "text-blue-600",
		},
		{
			id: "kyousou",
			title: "collaborativeLearning",
			description: "interdisciplinaryLearning",
			icon: iconMap.Users,
			color: "text-orange-600",
		},
		{
			id: "sxgx",
			title: "sxgxdx",
			description: "sustainableTransformation",
			icon: iconMap.Recycle,
			color: "text-red-600",
		},
	],
	"new-faculty": [
		{
			id: "infoDesign",
			title: "infoDesignFaculty",
			description: "designForNeeds",
			icon: iconMap.Tool,
			color: "text-blue-600",
		},
		{
			id: "mediaInfo",
			title: "mediaInfoFaculty",
			description: "mediaTechFusion",
			icon: iconMap.Camera,
			color: "text-purple-600",
		},
		{
			id: "infoTech",
			title: "infoTechFaculty",
			description: "pioneeringFuture",
			icon: iconMap.Cpu,
			color: "text-indigo-600",
		},
		{
			id: "bioChem",
			title: "bioChemFaculty",
			description: "exploringLifeChem",
			icon: iconMap.Beaker,
			color: "text-green-600",
		},
		{
			id: "eng",
			title: "engineeringFaculty",
			description: "supportingSociety",
			icon: iconMap.Wrench,
			color: "text-orange-600",
		},
		{
			id: "arch",
			title: "architectureFaculty",
			description: "designingSpaces",
			icon: iconMap.Home,
			color: "text-teal-600",
		},
	],
	learning: [
		{
			id: "educationMethod",
			title: "educationalMethods",
			description: "problemSolvingPrograms",
			icon: iconMap.Target,
			color: "text-blue-500",
		},
		{
			id: "collab",
			title: "collaborativeLearning2",
			description: "earlyResearch",
			icon: iconMap.Puzzle,
			color: "text-green-600",
		},
		{
			id: "intern",
			title: "internships",
			description: "corporateExperience",
			icon: iconMap.Briefcase,
			color: "text-orange-600",
		},
		{
			id: "curriculum",
			title: "curriculum",
			description: "overview",
			icon: iconMap.FileText,
			color: "text-emerald-600",
		},
	],
	"campus-life": [
		{
			id: "dining",
			title: "cafeteria",
			description: "cafeteriaInfo",
			icon: iconMap.Utensils,
			color: "text-yellow-600",
		},
		{
			id: "dorm",
			title: "dormitories",
			description: "housingSupport",
			icon: iconMap.Building,
			color: "text-teal-600",
		},
		{
			id: "extracurricular",
			title: "extracurricular",
			description: "clubsProjects",
			icon: iconMap.Music,
			color: "text-pink-500",
		},
		{
			id: "support",
			title: "studentSupport",
			description: "healthSupport",
			icon: iconMap.Heart,
			color: "text-gray-500",
		},
		{
			id: "bus",
			title: "interCampusBus",
			description: "serviceInfo",
			icon: iconMap.Bus,
			color: "text-green-500",
		},
	],
	admission: [
		{
			id: "admission",
			title: "admissions",
			description: "admissionsInfo",
			icon: iconMap.GraduationCap,
			color: "text-indigo-500",
		},
	],
	career: [
		{
			id: "career",
			title: "careerPaths",
			description: "employment",
			icon: iconMap.Target,
			color: "text-blue600",
		},
	],
	global: [
		{
			id: "global",
			title: "global",
			description: "internationalExchange",
			icon: iconMap.Globe,
			color: "text-cyan-500",
		},
	],
	research: [
		{
			id: "research",
			title: "researchActivities",
			description: "researchInstitutes",
			icon: iconMap.Microscope,
			color: "text-red-500",
		},
	],
	tuition: [
		{
			id: "tuition",
			title: "tuition",
			description: "costsSupport",
			icon: iconMap.Wallet,
			color: "text-green-500",
		},
	],
};

// サブサブカテゴリーのマッピング
export const subSubCategories: Record<string, Category[]> = {
	// about サブカテゴリー
	bunri: [
		{
			id: "bunri-komyunikeeshon",
			title: "communication",
			description: "studentExchange",
			icon: iconMap.MessageCircle,
			color: "text-emerald-700",
		},
		{
			id: "bunri-aratanakachisouzou",
			title: "valueCreation",
			description: "innovativePerspectives",
			icon: iconMap.Lightbulb,
			color: "text-orange-700",
		},
		{
			id: "bunri-kadaitsuikyuu",
			title: "problemPursuit",
			description: "solvingSocialIssues",
			icon: iconMap.Target,
			color: "text-blue-700",
		},
	],
	shakaijissou: [
		{
			id: "shakaijissou-jissenkyouiku",
			title: "practicalEducation",
			description: "practicalSkills",
			icon: Tool,
			color: "text-blue-700",
		},
		{
			id: "shakaijissou-sangakukyoudo",
			title: "industryAcademia",
			description: "collaborativeResearch",
			icon: iconMap.Handshake,
			color: "text-indigo-700",
		},
	],
	kyousou: [
		{
			id: "kyousou-sedai",
			title: "generations",
			description: "learningAcrossGenerations",
			icon: iconMap.Users,
			color: "text-purple-700",
		},
		{
			id: "kyousou-bunya",
			title: "fields",
			description: "learningAcrossFields",
			icon: iconMap.Puzzle,
			color: "text-orange-700",
		},
		{
			id: "kyousou-bunka",
			title: "culture",
			description: "learningAcrossCultures",
			icon: iconMap.Globe,
			color: "text-blue-700",
		},
	],
	sxgx: [
		{
			id: "sxgx-sx",
			title: "sx",
			description: "sustainability",
			icon: iconMap.Leaf,
			color: "text-green-700",
		},
		{
			id: "sxgx-gx",
			title: "gx",
			description: "decarbonization",
			icon: iconMap.Recycle,
			color: "text-teal-700",
		},
		{
			id: "sxgx-dx",
			title: "dx",
			description: "digitalTransformation",
			icon: iconMap.Cpu,
			color: "text-purple-700",
		},
	],
	// 情報デザイン
	infoDesign: [
		{
			id: "infoDesign-keieijoho",
			title: "businessInfoDept",
			description: "fusingManagementInfo",
			icon: iconMap.BarChart,
			color: "text-blue-700",
		},
		{
			id: "infoDesign-kankyoudesign",
			title: "environmentalDesignDept",
			description: "designingSustainableSociety",
			icon: iconMap.Leaf,
			color: "text-emerald-700",
		},
	],
	// メディア情報
	mediaInfo: [
		{
			id: "mediaInfo-mediajouhou",
			title: "mediaInfoDept",
			description: "pursuingMediaExpressions",
			icon: iconMap.Film,
			color: "text-purple-700",
		},
		{
			id: "mediaInfo-shinrijouhou",
			title: "psychologicalInfoDept",
			description: "designingForTheMind",
			icon: iconMap.Brain,
			color: "text-amber-700",
		},
	],
	// 情報理工学
	infoTech: [
		{
			id: "infoTech-johokogaku",
			title: "infoEngineeringDept",
			description: "foundationOfInfoScience",
			icon: iconMap.Code,
			color: "text-indigo-700",
		},
		{
			id: "infoTech-chinousystem",
			title: "intelligentInfoSystemsDept",
			description: "developingAISystems",
			icon: iconMap.Database,
			color: "text-blue-700",
		},
		{
			id: "infoTech-robotics",
			title: "roboticsDept",
			description: "contributingWithRobotics",
			icon: iconMap.Cpu,
			color: "text-green-700",
		},
	],
	// バイオ・化学
	bioChem: [
		{
			id: "bioChem-ouyoukagaku",
			title: "environmentalAppliedChemDept",
			description: "ecoFriendlyChem",
			icon: iconMap.Beaker,
			color: "text-green-700",
		},
		{
			id: "bioChem-seimeibio",
			title: "lifeAppliedBioDept",
			description: "researchingLifeScienceApps",
			icon: iconMap.Microscope,
			color: "text-emerald-700",
		},
	],
	// 工学部
	eng: [
		{
			id: "eng-kikaikougaku",
			title: "mechanicalEngineeringDept",
			description: "designingMechanicalSystems",
			icon: iconMap.Tool,
			color: "text-orange-700",
		},
		{
			id: "eng-senshinkikai",
			title: "advancedMechanicalSystemsDept",
			description: "creatingAdvancedSystems",
			icon: iconMap.Cpu,
			color: "text-red-700",
		},
		{
			id: "eng-koukuuuchuu",
			title: "aerospaceEngineeringDept",
			description: "learningAerospaceTech",
			icon: iconMap.Plane,
			color: "text-indigo-700",
		},
		{
			id: "eng-denkienergy",
			title: "electricalEnergySystemsDept",
			description: "innovatingEnergyTech",
			icon: iconMap.Zap,
			color: "text-blue-700",
		},
		{
			id: "eng-denshijouhou",
			title: "electronicInfoSystemsDept",
			description: "trainingICTExperts",
			icon: iconMap.Smartphone,
			color: "text-green-700",
		},
		{
			id: "eng-kankyodoken",
			title: "environmentalCivilEngDept",
			description: "buildingSustainableInfrastructure",
			icon: iconMap.Building,
			color: "text-teal-700",
		},
	],
	// 建築学部
	arch: [
		{
			id: "arch-kenchikukougaku",
			title: "architectureDept",
			description: "learningArchitecturalTech",
			icon: iconMap.Ruler,
			color: "text-teal-700",
		},
		{
			id: "arch-kenchikudesign",
			title: "architecturalDesignDept",
			description: "honingArchitecturalCreativity",
			icon: iconMap.Tool,
			color: "text-blue-700",
		},
	],
	// learning
	educationMethod: [
		{
			id: "educationMethod-projDesign",
			title: "projectDesignEducation",
			description: "developingProblemSolvingSkills",
			icon: iconMap.Target,
			color: "text-blue-700",
		},
		{
			id: "educationMethod-cdio",
			title: "cdio",
			description: "practicalEngineeringEducation",
			icon: iconMap.Puzzle,
			color: "text-purple-700",
		},
	],
	// collab
	collab: [
		{
			id: "collab-coop",
			title: "coopEducation",
			description: "practicalEducationWithCompanies",
			icon: iconMap.Handshake,
			color: "text-green-700",
		},
	],
	// intern
	intern: [
		{
			id: "intern-domestic",
			title: "domesticInternships",
			description: "workExperienceInJapan",
			icon: iconMap.Briefcase,
			color: "text-orange-700",
		},
		{
			id: "intern-overseas",
			title: "overseasInternships",
			description: "developingGlobalPerspective",
			icon: iconMap.Plane,
			color: "text-blue-700",
		},
	],
	// curriculum
	curriculum: [
		{
			id: "curriculum-basic",
			title: "basicEducation",
			description: "acquiringBroadKnowledge",
			icon: iconMap.Book,
			color: "text-emerald-700",
		},
		{
			id: "curriculum-professional",
			title: "specializedEducation",
			description: "deepeningSpecializedFields",
			icon: iconMap.Code,
			color: "text-blue-700",
		},
		{
			id: "curriculum-project",
			title: "projectSubjects",
			description: "tacklingPracticalIssues",
			icon: iconMap.Rocket,
			color: "text-gray-700",
		},
	],
	// campus-life サブカテゴリー
	dining: [
		{
			id: "dining-laterra",
			title: "laTerra",
			description: "laTerraDesc",
			icon: iconMap.Utensils,
			color: "text-yellow-700",
		},
		{
			id: "dining-ilsole",
			title: "ilSole",
			description: "ilSoleDesc",
			icon: iconMap.Utensils,
			color: "text-yellow-700",
		},
		{
			id: "dining-energy",
			title: "energy",
			description: "energyDesc",
			icon: iconMap.Utensils,
			color: "text-yellow-700",
		},
		{
			id: "dining-acqua",
			title: "acqua",
			description: "acquaDesc",
			icon: iconMap.Utensils,
			color: "text-yellow-700",
		},
	],
	dorm: [
		{
			id: "dorm-kit",
			title: "kitDorms",
			description: "kitDormsDesc",
			icon: iconMap.Home,
			color: "text-teal-700",
		},
		{
			id: "dorm-support",
			title: "housingSupportDesk",
			description: "housingSupportDeskDesc",
			icon: iconMap.Compass,
			color: "text-gray-700",
		},
	],
	extracurricular: [
		{
			id: "extracurricular-yumekobo",
			title: "yumekoboProject",
			description: "yumekoboProjectDesc",
			icon: iconMap.Rocket,
			color: "text-pink-700",
		},
		{
			id: "extracurricular-projects",
			title: "projects",
			description: "studentLedActivities",
			icon: iconMap.Rocket,
			color: "text-blue-700",
		},
		{
			id: "extracurricular-clubs",
			title: "clubsCircles",
			description: "clubsCirclesDesc",
			icon: iconMap.Users,
			color: "text-pink-700",
		},
		{
			id: "extracurricular-festival",
			title: "kodaisai",
			description: "kodaisaiDesc",
			icon: iconMap.Music,
			color: "text-pink-700",
		},
	],
	support: [
		{
			id: "support-station",
			title: "studentStation",
			description: "studentStationDesc",
			icon: iconMap.Heart,
			color: "text-gray-700",
		},
		{
			id: "support-procedure",
			title: "proceduresCerts",
			description: "proceduresCertsDesc",
			icon: iconMap.Clipboard,
			color: "text-gray-700",
		},
	],
	bus: [
		{
			id: "bus-timetable",
			title: "timetable",
			description: "timetableDesc",
			icon: iconMap.Clock,
			color: "text-green-700",
		},
	],
	admission: [
		{
			id: "admission-newfac",
			title: "newFacultyEstablishment",
			description: "newFacultyEstablishment",
			icon: iconMap.School,
			color: "text-indigo-700",
		},
		{
			id: "admission-scholarship",
			title: "scholarshipEnhancement",
			description: "scholarshipEnhancement",
			icon: iconMap.Gift,
			color: "text-yellow-700",
		},
		{
			id: "admission-sougou",
			title: "comprehensiveSelection",
			description: "comprehensiveSelection",
			icon: iconMap.Users,
			color: "text-orange-700",
		},
		{
			id: "admission-ippan",
			title: "generalExamAReform",
			description: "generalExamAReform",
			icon: iconMap.FileText,
			color: "text-blue-700",
		},
		{
			id: "admission-todoufuken",
			title: "prefecturalSelection",
			description: "prefecturalSelection",
			icon: iconMap.MapIcon,
			color: "text-indigo-700",
		},
		{
			id: "admission-list",
			title: "variousAdmissions",
			description: "variousAdmissions",
			icon: iconMap.Clipboard,
			color: "text-violet-700",
		},
		{
			id: "admission-quota",
			title: "enrollmentCapacity",
			description: "enrollmentCapacity",
			icon: iconMap.Users,
			color: "text-orange-700",
		},
		{
			id: "admission-examSchedule",
			title: "examSchedule",
			description: "examSchedule",
			icon: iconMap.Calendar,
			color: "text-indigo-700",
		},
		{
			id: "admission-application",
			title: "applicationProcedure",
			description: "applicationProcedure",
			icon: iconMap.Clipboard,
			color: "text-blue-700",
		},
		{
			id: "admission-pastData",
			title: "pastData",
			description: "pastData",
			icon: iconMap.BarChart,
			color: "text-blue-700",
		},
	],
	career: [
		{
			id: "career-seminar",
			title: "firstYearSeminar",
			description: "careerFormationFoundation",
			icon: iconMap.Book,
			color: "text-gray-700",
		},
		{
			id: "career-careerCenter",
			title: "careerSupport",
			description: "jobHuntingSupport",
			icon: iconMap.Compass,
			color: "text-gray-700",
		},
		{
			id: "career-employment",
			title: "employmentRecord",
			description: "graduatesCareerPaths",
			icon: iconMap.TrendingUp,
			color: "text-blue-700",
		},
	],
	global: [
		{
			id: "global-studyabroad",
			title: "studyAbroadSupport",
			description: "overseasPrograms",
			icon: iconMap.Plane,
			color: "text-blue-700",
		},
		{
			id: "global-english",
			title: "englishEducation",
			description: "globalCommunicationSkills",
			icon: iconMap.MessageCircle,
			color: "text-amber-700",
		},
		{
			id: "global-exchange",
			title: "internationalExchange2",
			description: "exchangeWithUniversities",
			icon: iconMap.Globe,
			color: "text-cyan-700",
		},
	],
	research: [
		{
			id: "research-activities",
			title: "researchActivities",
			description: "researchActivities",
			icon: iconMap.Microscope,
			color: "text-red-700",
		},
	],
	tuition: [
		{
			id: "tuition-fee",
			title: "tuition2",
			description: "tuitionInfo",
			icon: iconMap.DollarSign,
			color: "text-blue-700",
		},
		{
			id: "tuition-scholarship",
			title: "specialScholarship",
			description: "supportingOutstandingStudents",
			icon: iconMap.Medal,
			color: "text-yellow-700",
		},
		{
			id: "tuition-newScholarship",
			title: "newScholarship",
			description: "strengtheningFinancialSupport",
			icon: iconMap.Gift,
			color: "text-green-700",
		},
	],
};
